export const quotaScheduleEn = {
 title:"Reset schedules", tab:"Auto-reset", userTitle:"Automatic quota reset", subtitle:"Reset used Telemt quotas while preserving limits and panel history.",
 common:"Common schedule", commonNote:"For users inheriting the common rule", enabled:"Common enabled", disabled:"Common disabled", independent:"Custom schedules work independently. Disabling the common schedule does not disable individual schedules.",
 custom:"Custom schedule", excluded:"Excluded", overrides:"Individual settings", inherit:"Inherit common", off:"Disable", offNote:"Do not reset automatically", customNote:"Independent of the common rule", inherited:"Common schedule",
 interval:"Every N days", kind:"Schedule type", frequency:"Frequency", days:"Number of days", dayForms:["day","days","days"], daysHint:"30 days is an interval, not the first day of each month.", start:"First run date", time:"Time", gridNote:"Calendar days are counted from this date in the selected timezone. Manual resets do not shift the schedule.",
 cron:"Cron expression", cronFields:"Minute · hour · day of month · month · weekday", cronNote:"Five fields, without a command or seconds. Sunday is 0, 7 or SUN. When both day of month and weekday are restricted, either may match.", daily:"Every day", monday:"On Mondays", monthly:"First of month", cronHelp:"Cron help",
 timezone:"Timezone", oneZone:"One timezone for all schedules", server:"Server", zoneNote:"Also applies to individual schedules. Choosing the server timezone saves its current value.", userZoneNote:"The timezone is shared across the panel; change it in the common schedule.",
 preview:"Run preview", upcoming:"Upcoming runs", afterEnable:"After enabling", next:"Next reset", then:"Then", previewNote:"Dates are calculated by the panel in the selected timezone. Nonexistent daylight-saving times are skipped; repeated times run once.",
 recovery:"After downtime", catchup:"One missed reset", catchupNote:"After recovery, perform one reset even if several periods were missed. Then continue the normal schedule.", unknownNote:"An operation already started is not replayed after a restart. If its result is unknown, check used quotas manually.",
 noSchedule:"No automatic reset scheduled", manualAvailable:"Manual reset remains available.", edit:"Configure auto-reset", commonLink:"Common schedule", dirty:"Unsaved changes", unchanged:"Settings unchanged", save:"Save schedule", saved:"Schedule saved", saveNote:"Saving changes future runs only and does not reset quotas immediately.", reload:"Load current settings", pending:"Checking schedule…", overdue:"Waiting to run after recovery", last:"Last automatic reset", confirmed:"Confirmed", rejected:"Rejected", unknown:"Unknown", remaining:"Not sent", runTotal:"In operation", noUsers:"No eligible users", review:"Review the result", complete:"Completed", running:"Running", noHistory:"No runs yet", tracked:"Saved exceptions to the common schedule", period:"Interval", cronRule:"Cron schedule", inheritedOff:"The common schedule is currently disabled.",
} as const;
